-- Generated by RTK from grammar 'Sandbox'. Do not edit by hand.
-- v1 pretty-printer (task 9): correctness-first, not pretty. Emits exactly
-- one space between tokens, with no indentation or alignment. The only
-- guarantee is the semantic round-trip parse (print ast) == ast; comments
-- and the original whitespace are not recovered (the AST is lossy).
module SandboxPP where
import SandboxParser

ppSandbox :: Sandbox -> String
ppSandbox (Ctr__Sandbox__0 _ x1) = unwords ["tok_Sandbox_dummy_0", (ppSandbox x1), "tok_Sandbox_dummy_0"]
ppSandbox (Anti_Sandbox x1) = unwords [x1]
ppSandbox (Ctr__Sandbox__1 _ x1) = unwords [x1]