-- ncc: a tiny C compiler (Nora Sandler's "Writing a C Compiler"), with the
-- whole front end generated by RTK from c.pg.
--
-- Usage: ncc <file.c>
-- Produces an executable next to the source file (test-suite contract of
-- https://github.com/nlsandler/write_a_c_compiler), going through gcc for
-- assembling and linking.
module Main (main) where

import Control.Monad (when)
import System.Directory (removeFile)
import System.Environment (getArgs)
import System.Exit (ExitCode (..), exitFailure)
import System.FilePath (dropExtension, replaceExtension)
import System.IO (hPutStrLn, stderr)
import System.Process (rawSystem)

import CLexer (scanTokens)
import CParser (parseC)
import Resolve (resolve)
import Codegen (codegen)
import Emit (emit)

main :: IO ()
main = do
  args <- getArgs
  case args of
    [path] -> compileFile path
    _ -> do
      hPutStrLn stderr "usage: ncc <file.c>"
      exitFailure

compileFile :: FilePath -> IO ()
compileFile path = do
  src <- readFile path
  -- Lexical, syntax, and semantic errors all arrive as Left, before any output
  -- file is created: invalid programs exit non-zero and leave no artifacts.
  -- resolve runs between parse and codegen; its var->offset map feeds codegen.
  asm <- case scanTokens src >>= parseC of
    Left err -> reject err
    Right ast -> case resolve ast of
      Left err -> reject err
      Right varmap -> return (codegen varmap ast)
  let asmPath = replaceExtension path "s"
      exePath = dropExtension path
  -- emit renders the program's instruction AST; the GNU-stack note is
  -- file-level ELF metadata, identical for every program and not modelled by
  -- the assembly grammar, so the driver appends it here next to the gcc call
  -- rather than threading it through codegen or the round-trippable emitter.
  writeFile asmPath (emit asm ++ gnuStackNote)
  rc <- rawSystem "gcc" [asmPath, "-o", exePath]
  removeFile asmPath
  when (rc /= ExitSuccess) exitFailure
  where
    reject err = do hPutStrLn stderr (path ++ ": " ++ err); exitFailure

-- Marks the stack non-executable. Without this section ld warns "missing
-- .note.GNU-stack section implies executable stack" on every link. Linux/ELF
-- and x86 (@progbits) specific; a Mach-O or ARM port would change or drop it.
gnuStackNote :: String
gnuStackNote = ".section .note.GNU-stack,\"\",@progbits\n"
