-- ncc: a tiny C compiler (stage 1 of Nora Sandler's "Writing a C Compiler"),
-- with the whole front end generated by RTK from c.pg.
--
-- Usage: ncc <file.c>
-- Produces an executable next to the source file (test-suite contract of
-- https://github.com/nlsandler/write_a_c_compiler), going through gcc for
-- assembling and linking.
module Main (main) where

import Control.Exception (evaluate)
import Control.Monad (when)
import System.Directory (removeFile)
import System.Environment (getArgs)
import System.Exit (ExitCode (..), exitFailure)
import System.FilePath (dropExtension, replaceExtension)
import System.IO (hPutStrLn, stderr)
import System.Process (rawSystem)

import CLexer (alexScanTokens)
import CParser (Program, parseC)
import Codegen (codegen)

main :: IO ()
main = do
  args <- getArgs
  case args of
    [path] -> compileFile path
    _ -> do
      hPutStrLn stderr "usage: ncc <file.c>"
      exitFailure

compileFile :: FilePath -> IO ()
compileFile path = do
  src <- readFile path
  -- Force the full parse before any output file is created: lexically or
  -- syntactically invalid programs must exit non-zero without leaving
  -- artifacts behind (lexer/parser errors arrive lazily as calls to error).
  ast <- evaluate (forceParse src)
  let asmPath = replaceExtension path "s"
      exePath = dropExtension path
  writeFile asmPath (codegen ast)
  rc <- rawSystem "gcc" [asmPath, "-o", exePath]
  removeFile asmPath
  when (rc /= ExitSuccess) exitFailure

forceParse :: String -> Program
forceParse src =
  let ast = parseC (alexScanTokens src)
  in length (show ast) `seq` ast
