-- ncc: a tiny C compiler (stage 1 of Nora Sandler's "Writing a C Compiler"),
-- with the whole front end generated by RTK from c.pg.
--
-- Usage: ncc <file.c>
-- Produces an executable next to the source file (test-suite contract of
-- https://github.com/nlsandler/write_a_c_compiler), going through gcc for
-- assembling and linking.
module Main (main) where

import Control.Monad (when)
import System.Directory (removeFile)
import System.Environment (getArgs)
import System.Exit (ExitCode (..), exitFailure)
import System.FilePath (dropExtension, replaceExtension)
import System.IO (hPutStrLn, stderr)
import System.Process (rawSystem)

import CLexer (scanTokens)
import CParser (Program, parseC)
import Codegen (codegen)
import Emit (emit)

main :: IO ()
main = do
  args <- getArgs
  case args of
    [path] -> compileFile path
    _ -> do
      hPutStrLn stderr "usage: ncc <file.c>"
      exitFailure

compileFile :: FilePath -> IO ()
compileFile path = do
  src <- readFile path
  -- Lexical and syntax errors arrive as Left, before any output file is
  -- created: invalid programs exit non-zero and leave no artifacts behind.
  ast <- case scanTokens src >>= parseC of
    Left err -> do
      hPutStrLn stderr $ path ++ ": " ++ err
      exitFailure
    Right ast -> return (ast :: Program)
  let asmPath = replaceExtension path "s"
      exePath = dropExtension path
  writeFile asmPath (emit (codegen ast))
  rc <- rawSystem "gcc" [asmPath, "-o", exePath]
  removeFile asmPath
  when (rc /= ExitSuccess) exitFailure
