-- Generated by RTK from grammar 'I14'. Do not edit by hand.
{
{-# LANGUAGE StandaloneDeriving, DeriveDataTypeable #-}
module I14Lexer(scanTokens, alexScanTokens, Token(..), PosToken(..), AlexPosn(..))
where
import Data.Data (Data)

 }
%wrapper "monad"


tokens :- "tok_Items_dummy_3" { simple Tk__tok_Items_dummy_3 }
          "tok_Label_dummy_2" { simple Tk__tok_Label_dummy_2 }
          "tok_Shape_dummy_1" { simple Tk__tok_Shape_dummy_1 }
          "tok_Start_dummy_4" { simple Tk__tok_Start_dummy_4 }
          "square" { simple Tk__tok_square_1 }
          "note" { simple Tk__tok_note_3 }
          "circle" { simple Tk__tok_circle_0 }
          "," { simple Tk__tok__coma__2 }
          ([\ \t\n]+) ;
          ([0-9]+) { simple1 $  Tk__num . (id) }
          ("$"  "Label"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Label . ((tail . dropWhile (/= ':'))) }
          ("$"  "Items"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Items . ((tail . dropWhile (/= ':'))) }
          ("$"  "Shape"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Shape . ((tail . dropWhile (/= ':'))) }
          ("$"  "Start"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Start . ((tail . dropWhile (/= ':'))) }
          . { rtkError }

{
data Token = EndOfFile |
             Tk__tok_Items_dummy_3 |
             Tk__tok_Label_dummy_2 |
             Tk__tok_Shape_dummy_1 |
             Tk__tok_Start_dummy_4 |
             Tk__tok_square_1 |
             Tk__tok_note_3 |
             Tk__tok_circle_0 |
             Tk__tok__coma__2 |
             Tk__num String |
             Tk__qq_Label String |
             Tk__qq_Items String |
             Tk__qq_Shape String |
             Tk__qq_Start String
             deriving (Show)

-- AlexPosn is defined by the alex wrapper, so the Data instance (required by
-- the parser's RtkPos position type) can only be attached via standalone
-- deriving - the same solution as the hand-written Lexer.x
deriving instance Data AlexPosn

-- A token together with the source position where it starts
data PosToken = PosToken { ptPos :: AlexPosn, ptToken :: Token }
                deriving (Show)

alexEOF = do
  (pos, _, _, _) <- alexGetInput
  return $ PosToken pos EndOfFile

-- Lex the input into a token stream, returning the positioned error message
-- on a lexical error (encoded as "LINE:COL:message", see rtkError below).
-- The returned list always ends with an EndOfFile token that carries the
-- position of the end of input, so parse errors at end of input can be
-- reported with a position too
scanTokens :: String -> Either String [PosToken]
scanTokens str = runAlex str $ do
  let loop toks = do tok <- alexMonadScan
                     case tok of
                       PosToken _ EndOfFile -> return $ reverse (tok : toks)
                       _ -> let toks' = tok : toks
                            in toks' `seq` loop toks'
  loop []

-- Thin compatibility wrapper: callers that have not switched to 'scanTokens'
-- get the error message thrown instead
alexScanTokens :: String -> [PosToken]
alexScanTokens str =
               case scanTokens str of
                  Right toks -> toks
                  Left err -> errorWithoutStackTrace err

simple1 :: (String -> Token) -> AlexInput -> Int -> Alex PosToken
simple1 t (pos, _, _, str) len = return $ PosToken pos (t (take len str))

simple :: Token -> AlexInput -> Int -> Alex PosToken
simple t (pos, _, _, _) len = return $ PosToken pos t

-- Encode the position as "LINE:COL:message" so callers can split it back out
-- into a structured position - the same encoding the rtk grammar lexer uses
rtkError ((AlexPn _ line column), _, _, str) len = alexError $ (show line) ++ ":" ++ (show column) ++ ":lexical error. Following chars: " ++ (take 10 str)

}