-- Generated by RTK from grammar 'Lc'. Do not edit by hand.
{
{-# LANGUAGE StandaloneDeriving, DeriveDataTypeable #-}
module LcLexer(scanTokens, alexScanTokens, Token(..), PosToken(..), AlexPosn(..))
where
import Data.Data (Data)

 }
%wrapper "monad"


tokens :- "tok_Expr_dummy_1" { simple Tk__tok_Expr_dummy_1 }
          "tok_Id_dummy_0" { simple Tk__tok_Id_dummy_0 }
          "tok_Lc_dummy_2" { simple Tk__tok_Lc_dummy_2 }
          "true" { simple Tk__tok_true_12 }
          "then" { simple Tk__tok_then_6 }
          "let" { simple Tk__tok_let_2 }
          "in" { simple Tk__tok_in_4 }
          "if" { simple Tk__tok_if_5 }
          "fn" { simple Tk__tok_fn_0 }
          "false" { simple Tk__tok_false_13 }
          "else" { simple Tk__tok_else_7 }
          "==" { simple Tk__tok__eql__eql__8 }
          "=" { simple Tk__tok__eql__3 }
          "->" { simple Tk__tok__minus__symbol__1 }
          "-" { simple Tk__tok__minus__10 }
          "+" { simple Tk__tok__plus__9 }
          "*" { simple Tk__tok__star__11 }
          ")" { simple Tk__tok__rparen__15 }
          "(" { simple Tk__tok__lparen__14 }
          ("--"  .*  [\n]) ;
          ([\ \t\n]+) ;
          ([a-z]  [a-zA-Z0-9_]*) { simple1 $  Tk__id . (id) }
          ([0-9]+) { simple1 $  Tk__num . (read) }
          ("$"  "Id"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Id . ((tail . dropWhile (/= ':'))) }
          ("$"  "Expr"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Expr . ((tail . dropWhile (/= ':'))) }
          ("$"  "Lc"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Lc . ((tail . dropWhile (/= ':'))) }
          . { rtkError }

{
data Token = EndOfFile |
             Tk__tok_Expr_dummy_1 |
             Tk__tok_Id_dummy_0 |
             Tk__tok_Lc_dummy_2 |
             Tk__tok_true_12 |
             Tk__tok_then_6 |
             Tk__tok_let_2 |
             Tk__tok_in_4 |
             Tk__tok_if_5 |
             Tk__tok_fn_0 |
             Tk__tok_false_13 |
             Tk__tok_else_7 |
             Tk__tok__eql__eql__8 |
             Tk__tok__eql__3 |
             Tk__tok__minus__symbol__1 |
             Tk__tok__minus__10 |
             Tk__tok__plus__9 |
             Tk__tok__star__11 |
             Tk__tok__rparen__15 |
             Tk__tok__lparen__14 |
             Tk__id String |
             Tk__num Int |
             Tk__qq_Id String |
             Tk__qq_Expr String |
             Tk__qq_Lc String
             deriving (Show)

-- AlexPosn is defined by the alex wrapper, so the Data instance (required by
-- the parser's RtkPos position type) can only be attached via standalone
-- deriving - the same solution as the hand-written Lexer.x
deriving instance Data AlexPosn

-- A token together with the source position where it starts
data PosToken = PosToken { ptPos :: AlexPosn, ptToken :: Token }
                deriving (Show)

alexEOF = do
  (pos, _, _, _) <- alexGetInput
  return $ PosToken pos EndOfFile

-- Lex the input into a token stream, returning the positioned error message
-- on a lexical error (encoded as "LINE:COL:message", see rtkError below).
-- The returned list always ends with an EndOfFile token that carries the
-- position of the end of input, so parse errors at end of input can be
-- reported with a position too
scanTokens :: String -> Either String [PosToken]
scanTokens str = runAlex str $ do
  let loop toks = do tok <- alexMonadScan
                     case tok of
                       PosToken _ EndOfFile -> return $ reverse (tok : toks)
                       _ -> let toks' = tok : toks
                            in toks' `seq` loop toks'
  loop []

-- Thin compatibility wrapper: callers that have not switched to 'scanTokens'
-- get the error message thrown instead
alexScanTokens :: String -> [PosToken]
alexScanTokens str =
               case scanTokens str of
                  Right toks -> toks
                  Left err -> errorWithoutStackTrace err

simple1 :: (String -> Token) -> AlexInput -> Int -> Alex PosToken
simple1 t (pos, _, _, str) len = return $ PosToken pos (t (take len str))

simple :: Token -> AlexInput -> Int -> Alex PosToken
simple t (pos, _, _, _) len = return $ PosToken pos t

-- Encode the position as "LINE:COL:message" so callers can split it back out
-- into a structured position - the same encoding the rtk grammar lexer uses
rtkError ((AlexPn _ line column), _, _, str) len = alexError $ (show line) ++ ":" ++ (show column) ++ ":lexical error. Following chars: " ++ (take 10 str)

}