-- Generated by RTK from grammar 'Block'. Do not edit by hand.
{
{-# LANGUAGE StandaloneDeriving, DeriveDataTypeable #-}
module BlockLexer(scanTokens, alexScanTokens, Token(..), PosToken(..), AlexPosn(..))
where
import Data.Data (Data)

 }
%wrapper "monad"


tokens :- "tok_Block_dummy_8" { simple Tk__tok_Block_dummy_8 }
          "tok_Exp_dummy_7" { simple Tk__tok_Exp_dummy_7 }
          "tok_Function_dummy_6" { simple Tk__tok_Function_dummy_6 }
          "tok_Ident_dummy_5" { simple Tk__tok_Ident_dummy_5 }
          "tok_ParamList_dummy_4" { simple Tk__tok_ParamList_dummy_4 }
          "tok_Program_dummy_9" { simple Tk__tok_Program_dummy_9 }
          "tok_Statement_dummy_3" { simple Tk__tok_Statement_dummy_3 }
          "tok_StatementList_dummy_2" { simple Tk__tok_StatementList_dummy_2 }
          "}" { simple Tk__tok__symbol__5 }
          "{" { simple Tk__tok__symbol__4 }
          "return" { simple Tk__tok_return_8 }
          "fn" { simple Tk__tok_fn_0 }
          "=" { simple Tk__tok__eql__6 }
          ";" { simple Tk__tok__semi__7 }
          "," { simple Tk__tok__coma__3 }
          ")" { simple Tk__tok__rparen__2 }
          "(" { simple Tk__tok__lparen__1 }
          ([\ \t\n\r]+) ;
          ([0-9]+) { simple1 $  Tk__num . (read) }
          ([a-zA-Z_]  [a-zA-Z0-9_]*) { simple1 $  Tk__id . (id) }
          ("$"  "Ident"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Ident . ((tail . dropWhile (/= ':'))) }
          ("$"  "Exp"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Exp . ((tail . dropWhile (/= ':'))) }
          ("$"  "Statement"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Statement . ((tail . dropWhile (/= ':'))) }
          ("$"  "StatementList"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_StatementList . ((tail . dropWhile (/= ':'))) }
          ("$"  "Block"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Block . ((tail . dropWhile (/= ':'))) }
          ("$"  "ParamList"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_ParamList . ((tail . dropWhile (/= ':'))) }
          ("$"  "Function"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Function . ((tail . dropWhile (/= ':'))) }
          ("$"  "Program"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Program . ((tail . dropWhile (/= ':'))) }
          . { rtkError }

{
data Token = EndOfFile |
             Tk__tok_Block_dummy_8 |
             Tk__tok_Exp_dummy_7 |
             Tk__tok_Function_dummy_6 |
             Tk__tok_Ident_dummy_5 |
             Tk__tok_ParamList_dummy_4 |
             Tk__tok_Program_dummy_9 |
             Tk__tok_Statement_dummy_3 |
             Tk__tok_StatementList_dummy_2 |
             Tk__tok__symbol__5 |
             Tk__tok__symbol__4 |
             Tk__tok_return_8 |
             Tk__tok_fn_0 |
             Tk__tok__eql__6 |
             Tk__tok__semi__7 |
             Tk__tok__coma__3 |
             Tk__tok__rparen__2 |
             Tk__tok__lparen__1 |
             Tk__num Int |
             Tk__id String |
             Tk__qq_Ident String |
             Tk__qq_Exp String |
             Tk__qq_Statement String |
             Tk__qq_StatementList String |
             Tk__qq_Block String |
             Tk__qq_ParamList String |
             Tk__qq_Function String |
             Tk__qq_Program String
             deriving (Show)

-- AlexPosn is defined by the alex wrapper, so the Data instance (required by
-- the parser's RtkPos position type) can only be attached via standalone
-- deriving - the same solution as the hand-written Lexer.x
deriving instance Data AlexPosn

-- A token together with the source position where it starts
data PosToken = PosToken { ptPos :: AlexPosn, ptToken :: Token }
                deriving (Show)

alexEOF = do
  (pos, _, _, _) <- alexGetInput
  return $ PosToken pos EndOfFile

-- Lex the input into a token stream, returning the positioned error message
-- on a lexical error (encoded as "LINE:COL:message", see rtkError below).
-- The returned list always ends with an EndOfFile token that carries the
-- position of the end of input, so parse errors at end of input can be
-- reported with a position too
scanTokens :: String -> Either String [PosToken]
scanTokens str = runAlex str $ do
  let loop toks = do tok <- alexMonadScan
                     case tok of
                       PosToken _ EndOfFile -> return $ reverse (tok : toks)
                       _ -> let toks' = tok : toks
                            in toks' `seq` loop toks'
  loop []

-- Thin compatibility wrapper: callers that have not switched to 'scanTokens'
-- get the error message thrown instead
alexScanTokens :: String -> [PosToken]
alexScanTokens str =
               case scanTokens str of
                  Right toks -> toks
                  Left err -> errorWithoutStackTrace err

simple1 :: (String -> Token) -> AlexInput -> Int -> Alex PosToken
simple1 t (pos, _, _, str) len = return $ PosToken pos (t (take len str))

simple :: Token -> AlexInput -> Int -> Alex PosToken
simple t (pos, _, _, _) len = return $ PosToken pos t

-- Encode the position as "LINE:COL:message" so callers can split it back out
-- into a structured position - the same encoding the rtk grammar lexer uses
rtkError ((AlexPn _ line column), _, _, str) len = alexError $ (show line) ++ ":" ++ (show column) ++ ":lexical error. Following chars: " ++ (take 10 str)

}