-- Generated by RTK from grammar 'Poly'. Do not edit by hand.
{
{-# LANGUAGE StandaloneDeriving, DeriveDataTypeable #-}
module PolyLexer(scanTokens, alexScanTokens, Token(..), PosToken(..), AlexPosn(..))
where
import Data.Data (Data)

 }
%wrapper "monad"


tokens :- "tok_Decl_dummy_7" { simple Tk__tok_Decl_dummy_7 }
          "tok_DeclList_dummy_6" { simple Tk__tok_DeclList_dummy_6 }
          "tok_Expr_dummy_5" { simple Tk__tok_Expr_dummy_5 }
          "tok_Id_dummy_4" { simple Tk__tok_Id_dummy_4 }
          "tok_Param_dummy_3" { simple Tk__tok_Param_dummy_3 }
          "tok_Params_dummy_2" { simple Tk__tok_Params_dummy_2 }
          "tok_Poly_dummy_8" { simple Tk__tok_Poly_dummy_8 }
          "true" { simple Tk__tok_true_15 }
          "then" { simple Tk__tok_then_8 }
          "rec" { simple Tk__tok_rec_1 }
          "let" { simple Tk__tok_let_0 }
          "in" { simple Tk__tok_in_6 }
          "if" { simple Tk__tok_if_7 }
          "fix" { simple Tk__tok_fix_10 }
          "false" { simple Tk__tok_false_16 }
          "else" { simple Tk__tok_else_9 }
          "\" { simple Tk__tok__symbol__4 }
          "==" { simple Tk__tok__eql__eql__11 }
          "=" { simple Tk__tok__eql__2 }
          ";" { simple Tk__tok__semi__3 }
          "->" { simple Tk__tok__minus__symbol__5 }
          "-" { simple Tk__tok__minus__13 }
          "+" { simple Tk__tok__plus__12 }
          "*" { simple Tk__tok__star__14 }
          ")" { simple Tk__tok__rparen__18 }
          "(" { simple Tk__tok__lparen__17 }
          ("--"  .*  [\n]) ;
          ([\ \t\n]+) ;
          ([a-z]  [a-zA-Z0-9_]*) { simple1 $  Tk__id . (id) }
          ([0-9]+) { simple1 $  Tk__num . (read) }
          ("$"  "Id"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Id . ((tail . dropWhile (/= ':'))) }
          ("$"  "Param"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Param . ((tail . dropWhile (/= ':'))) }
          ("$"  "Params"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Params . ((tail . dropWhile (/= ':'))) }
          ("$"  "Expr"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Expr . ((tail . dropWhile (/= ':'))) }
          ("$"  "Decl"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Decl . ((tail . dropWhile (/= ':'))) }
          ("$"  "DeclList"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_DeclList . ((tail . dropWhile (/= ':'))) }
          ("$"  "Poly"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Poly . ((tail . dropWhile (/= ':'))) }
          . { rtkError }

{
data Token = EndOfFile |
             Tk__tok_Decl_dummy_7 |
             Tk__tok_DeclList_dummy_6 |
             Tk__tok_Expr_dummy_5 |
             Tk__tok_Id_dummy_4 |
             Tk__tok_Param_dummy_3 |
             Tk__tok_Params_dummy_2 |
             Tk__tok_Poly_dummy_8 |
             Tk__tok_true_15 |
             Tk__tok_then_8 |
             Tk__tok_rec_1 |
             Tk__tok_let_0 |
             Tk__tok_in_6 |
             Tk__tok_if_7 |
             Tk__tok_fix_10 |
             Tk__tok_false_16 |
             Tk__tok_else_9 |
             Tk__tok__symbol__4 |
             Tk__tok__eql__eql__11 |
             Tk__tok__eql__2 |
             Tk__tok__semi__3 |
             Tk__tok__minus__symbol__5 |
             Tk__tok__minus__13 |
             Tk__tok__plus__12 |
             Tk__tok__star__14 |
             Tk__tok__rparen__18 |
             Tk__tok__lparen__17 |
             Tk__id String |
             Tk__num Int |
             Tk__qq_Id String |
             Tk__qq_Param String |
             Tk__qq_Params String |
             Tk__qq_Expr String |
             Tk__qq_Decl String |
             Tk__qq_DeclList String |
             Tk__qq_Poly String
             deriving (Show)

-- AlexPosn is defined by the alex wrapper, so the Data instance (required by
-- the parser's RtkPos position type) can only be attached via standalone
-- deriving - the same solution as the hand-written Lexer.x
deriving instance Data AlexPosn

-- A token together with the source position where it starts
data PosToken = PosToken { ptPos :: AlexPosn, ptToken :: Token }
                deriving (Show)

alexEOF = do
  (pos, _, _, _) <- alexGetInput
  return $ PosToken pos EndOfFile

-- Lex the input into a token stream, returning the positioned error message
-- on a lexical error (encoded as "LINE:COL:message", see rtkError below).
-- The returned list always ends with an EndOfFile token that carries the
-- position of the end of input, so parse errors at end of input can be
-- reported with a position too
scanTokens :: String -> Either String [PosToken]
scanTokens str = runAlex str $ do
  let loop toks = do tok <- alexMonadScan
                     case tok of
                       PosToken _ EndOfFile -> return $ reverse (tok : toks)
                       _ -> let toks' = tok : toks
                            in toks' `seq` loop toks'
  loop []

-- Thin compatibility wrapper: callers that have not switched to 'scanTokens'
-- get the error message thrown instead
alexScanTokens :: String -> [PosToken]
alexScanTokens str =
               case scanTokens str of
                  Right toks -> toks
                  Left err -> errorWithoutStackTrace err

simple1 :: (String -> Token) -> AlexInput -> Int -> Alex PosToken
simple1 t (pos, _, _, str) len = return $ PosToken pos (t (take len str))

simple :: Token -> AlexInput -> Int -> Alex PosToken
simple t (pos, _, _, _) len = return $ PosToken pos t

-- Encode the position as "LINE:COL:message" so callers can split it back out
-- into a structured position - the same encoding the rtk grammar lexer uses
rtkError ((AlexPn _ line column), _, _, str) len = alexError $ (show line) ++ ":" ++ (show column) ++ ":lexical error. Following chars: " ++ (take 10 str)

}