-- Generated by RTK from grammar 'Stlc'. Do not edit by hand.
{
{-# LANGUAGE DeriveDataTypeable #-}
module StlcParser where
import qualified Data.Generics as Gen
import qualified StlcLexer as L (Token(..), PosToken(..), AlexPosn(..), alexScanTokens)
}

%name parseStlc
%tokentype { L.PosToken }
%monad { Either String }
%error { parseError }

%token

rtk__eof { L.PosToken _ L.EndOfFile }
tok_Expr_dummy_2 { L.PosToken _ L.Tk__tok_Expr_dummy_2 }
tok_Id_dummy_1 { L.PosToken _ L.Tk__tok_Id_dummy_1 }
tok_Stlc_dummy_3 { L.PosToken _ L.Tk__tok_Stlc_dummy_3 }
tok_Ty_dummy_0 { L.PosToken _ L.Tk__tok_Ty_dummy_0 }
tok_true_13 { L.PosToken _ L.Tk__tok_true_13 }
tok_then_7 { L.PosToken _ L.Tk__tok_then_7 }
tok_let_3 { L.PosToken _ L.Tk__tok_let_3 }
tok_in_5 { L.PosToken _ L.Tk__tok_in_5 }
tok_if_6 { L.PosToken _ L.Tk__tok_if_6 }
tok_false_14 { L.PosToken _ L.Tk__tok_false_14 }
tok_else_8 { L.PosToken _ L.Tk__tok_else_8 }
tok__symbol__0 { L.PosToken _ L.Tk__tok__symbol__0 }
tok_Int_18 { L.PosToken _ L.Tk__tok_Int_18 }
tok_Bool_19 { L.PosToken _ L.Tk__tok_Bool_19 }
tok__eql__eql__9 { L.PosToken _ L.Tk__tok__eql__eql__9 }
tok__eql__4 { L.PosToken _ L.Tk__tok__eql__4 }
tok__colon__1 { L.PosToken _ L.Tk__tok__colon__1 }
tok__dot__2 { L.PosToken _ L.Tk__tok__dot__2 }
tok__minus__symbol__17 { L.PosToken _ L.Tk__tok__minus__symbol__17 }
tok__minus__11 { L.PosToken _ L.Tk__tok__minus__11 }
tok__plus__10 { L.PosToken _ L.Tk__tok__plus__10 }
tok__star__12 { L.PosToken _ L.Tk__tok__star__12 }
tok__rparen__16 { L.PosToken _ L.Tk__tok__rparen__16 }
tok__lparen__15 { L.PosToken _ L.Tk__tok__lparen__15 }
id { L.PosToken _ (L.Tk__id _) }
num { L.PosToken _ (L.Tk__num _) }
qq_Id { L.PosToken _ (L.Tk__qq_Id _) }
qq_Ty { L.PosToken _ (L.Tk__qq_Ty _) }
qq_Expr { L.PosToken _ (L.Tk__qq_Expr _) }
qq_Stlc { L.PosToken _ (L.Tk__qq_Stlc _) }

%%

Stlc__top : Stlc rtk__eof { $1 }

Stlc : tok_Stlc_dummy_3 Stlc tok_Stlc_dummy_3 { Ctr__Stlc__0 (rtkPosOf $1) $2 } |
       tok_Expr_dummy_2 Expr tok_Expr_dummy_2 { Ctr__Stlc__1 (rtkPosOf $1) $2 } |
       tok_Id_dummy_1 Id tok_Id_dummy_1 { Ctr__Stlc__2 (rtkPosOf $1) $2 } |
       tok_Ty_dummy_0 Ty tok_Ty_dummy_0 { Ctr__Stlc__3 (rtkPosOf $1) $2 }

Stlc : qq_Stlc { Anti_Stlc (tkVal_qq_Stlc $1) } |
       Expr { Ctr__Stlc__4 (rtkPosOf $1) $1 }

Atom : qq_Expr { Anti_Expr (tkVal_qq_Expr $1) } |
       num { Ctr__Expr__0 (rtkPosOf $1) (tkVal_num $1) } |
       tok_true_13 { Ctr__Expr__1 (rtkPosOf $1) } |
       tok_false_14 { Ctr__Expr__2 (rtkPosOf $1) } |
       Id { Ctr__Expr__3 (rtkPosOf $1) $1 } |
       tok__lparen__15 Expr tok__rparen__16 { $2 }

App : App Atom { Ctr__Expr__5 (rtkPosOf $1) $1 $2 } |
      Atom { $1 }

Mul : Mul tok__star__12 App { Ctr__Expr__7 (rtkPosOf $1) $1 $3 } |
      App { $1 }

Add : Add tok__plus__10 Mul { Ctr__Expr__9 (rtkPosOf $1) $1 $3 } |
      Add tok__minus__11 Mul { Ctr__Expr__10 (rtkPosOf $1) $1 $3 } |
      Mul { $1 }

Eq : Eq tok__eql__eql__9 Add { Ctr__Expr__12 (rtkPosOf $1) $1 $3 } |
     Add { $1 }

Expr : tok__symbol__0 Id tok__colon__1 Ty tok__dot__2 Expr { Ctr__Expr__14 (rtkPosOf $1) $2 $4 $6 } |
       tok_let_3 Id tok__eql__4 Expr tok_in_5 Expr { Ctr__Expr__15 (rtkPosOf $1) $2 $4 $6 } |
       tok_if_6 Expr tok_then_7 Expr tok_else_8 Expr { Ctr__Expr__16 (rtkPosOf $1) $2 $4 $6 } |
       Eq { $1 }

Id : qq_Id { Anti_Id (tkVal_qq_Id $1) } |
     id { Ctr__Id__0 (rtkPosOf $1) (tkVal_id $1) }

TyAtom : qq_Ty { Anti_Ty (tkVal_qq_Ty $1) } |
         tok_Int_18 { Ctr__Ty__0 (rtkPosOf $1) } |
         tok_Bool_19 { Ctr__Ty__1 (rtkPosOf $1) } |
         tok__lparen__15 Ty tok__rparen__16 { $2 }

Ty : TyAtom tok__minus__symbol__17 Ty { Ctr__Ty__3 (rtkPosOf $1) $1 $3 } |
     TyAtom { $1 }


{
parseError :: [L.PosToken] -> Either String a
parseError [] = Left "unexpected end of input"
parseError (L.PosToken (L.AlexPn _ line col) tok : _) =
    Left $ show line ++ ":" ++ show col ++ ":unexpected " ++ showRtkToken tok

-- Render a token the way it appears in the source, for error messages
showRtkToken :: L.Token -> String
showRtkToken L.EndOfFile = "end of input"
showRtkToken L.Tk__tok_Expr_dummy_2 = "'tok_Expr_dummy_2'"
showRtkToken L.Tk__tok_Id_dummy_1 = "'tok_Id_dummy_1'"
showRtkToken L.Tk__tok_Stlc_dummy_3 = "'tok_Stlc_dummy_3'"
showRtkToken L.Tk__tok_Ty_dummy_0 = "'tok_Ty_dummy_0'"
showRtkToken L.Tk__tok_true_13 = "'true'"
showRtkToken L.Tk__tok_then_7 = "'then'"
showRtkToken L.Tk__tok_let_3 = "'let'"
showRtkToken L.Tk__tok_in_5 = "'in'"
showRtkToken L.Tk__tok_if_6 = "'if'"
showRtkToken L.Tk__tok_false_14 = "'false'"
showRtkToken L.Tk__tok_else_8 = "'else'"
showRtkToken L.Tk__tok__symbol__0 = "'\\'"
showRtkToken L.Tk__tok_Int_18 = "'Int'"
showRtkToken L.Tk__tok_Bool_19 = "'Bool'"
showRtkToken L.Tk__tok__eql__eql__9 = "'=='"
showRtkToken L.Tk__tok__eql__4 = "'='"
showRtkToken L.Tk__tok__colon__1 = "':'"
showRtkToken L.Tk__tok__dot__2 = "'.'"
showRtkToken L.Tk__tok__minus__symbol__17 = "'->'"
showRtkToken L.Tk__tok__minus__11 = "'-'"
showRtkToken L.Tk__tok__plus__10 = "'+'"
showRtkToken L.Tk__tok__star__12 = "'*'"
showRtkToken L.Tk__tok__rparen__16 = "')'"
showRtkToken L.Tk__tok__lparen__15 = "'('"
showRtkToken (L.Tk__id v) = "id " ++ show v
showRtkToken (L.Tk__num v) = "num " ++ show v
showRtkToken (L.Tk__qq_Id v) = "qq_Id " ++ show v
showRtkToken (L.Tk__qq_Ty v) = "qq_Ty " ++ show v
showRtkToken (L.Tk__qq_Expr v) = "qq_Expr " ++ show v
showRtkToken (L.Tk__qq_Stlc v) = "qq_Stlc " ++ show v

-- Source position of a node: every constructor except the Anti_* splice
-- artifacts stores the position of its alternative's first symbol in its
-- first field. Positions are transparent for equality and ordering, so two
-- ASTs that differ only in source positions (e.g. a quasi-quote parsed at
-- compile time vs the same construct parsed at run time) compare equal.
newtype RtkPos = RtkPos L.AlexPosn deriving (Show, Gen.Data, Gen.Typeable)
instance Eq RtkPos where _ == _ = True
instance Ord RtkPos where compare _ _ = EQ

-- The position used where no source token exists: empty productions, empty
-- lists, absent optionals and Anti_* quasi-quote splices
rtkNoPos :: RtkPos
rtkNoPos = RtkPos (L.AlexPn 0 0 0)

class RtkPosOf a where
    rtkPosOf :: a -> RtkPos
instance RtkPosOf L.PosToken where
    rtkPosOf (L.PosToken p _) = RtkPos p
instance RtkPosOf a => RtkPosOf [a] where
    rtkPosOf (x : _) = rtkPosOf x
    rtkPosOf []      = rtkNoPos
instance RtkPosOf a => RtkPosOf (Maybe a) where
    rtkPosOf (Just x) = rtkPosOf x
    rtkPosOf Nothing  = rtkNoPos
-- A Char carries no position; this also covers String token payloads
instance RtkPosOf Char where
    rtkPosOf _ = rtkNoPos
instance RtkPosOf Int where rtkPosOf _ = rtkNoPos

-- Recover a token's payload from the whole positioned token: %token
-- bindings keep the L.PosToken so semantic actions can read its position
tkVal_id :: L.PosToken -> String
tkVal_id (L.PosToken _ (L.Tk__id v)) = v
tkVal_id t = error ("rtk internal error: token id expected, got " ++ showRtkToken (L.ptToken t))
tkVal_num :: L.PosToken -> Int
tkVal_num (L.PosToken _ (L.Tk__num v)) = v
tkVal_num t = error ("rtk internal error: token num expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_Id :: L.PosToken -> String
tkVal_qq_Id (L.PosToken _ (L.Tk__qq_Id v)) = v
tkVal_qq_Id t = error ("rtk internal error: token qq_Id expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_Ty :: L.PosToken -> String
tkVal_qq_Ty (L.PosToken _ (L.Tk__qq_Ty v)) = v
tkVal_qq_Ty t = error ("rtk internal error: token qq_Ty expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_Expr :: L.PosToken -> String
tkVal_qq_Expr (L.PosToken _ (L.Tk__qq_Expr v)) = v
tkVal_qq_Expr t = error ("rtk internal error: token qq_Expr expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_Stlc :: L.PosToken -> String
tkVal_qq_Stlc (L.PosToken _ (L.Tk__qq_Stlc v)) = v
tkVal_qq_Stlc t = error ("rtk internal error: token qq_Stlc expected, got " ++ showRtkToken (L.ptToken t))

data Stlc = Ctr__Stlc__0 RtkPos Stlc |
            Ctr__Stlc__1 RtkPos Expr |
            Ctr__Stlc__2 RtkPos Id |
            Ctr__Stlc__3 RtkPos Ty |
            Anti_Stlc String |
            Ctr__Stlc__4 RtkPos Expr
            deriving (Ord, Eq, Show, Gen.Data, Gen.Typeable)
instance RtkPosOf Stlc where
    rtkPosOf (Ctr__Stlc__0 p _) = p
    rtkPosOf (Ctr__Stlc__1 p _) = p
    rtkPosOf (Ctr__Stlc__2 p _) = p
    rtkPosOf (Ctr__Stlc__3 p _) = p
    rtkPosOf (Anti_Stlc _) = rtkNoPos
    rtkPosOf (Ctr__Stlc__4 p _) = p
data Expr = Anti_Expr String |
            Ctr__Expr__0 RtkPos Int |
            Ctr__Expr__1 RtkPos |
            Ctr__Expr__2 RtkPos |
            Ctr__Expr__3 RtkPos Id |
            Ctr__Expr__5 RtkPos Expr Expr |
            Ctr__Expr__7 RtkPos Expr Expr |
            Ctr__Expr__9 RtkPos Expr Expr |
            Ctr__Expr__10 RtkPos Expr Expr |
            Ctr__Expr__12 RtkPos Expr Expr |
            Ctr__Expr__14 RtkPos Id Ty Expr |
            Ctr__Expr__15 RtkPos Id Expr Expr |
            Ctr__Expr__16 RtkPos Expr Expr Expr
            deriving (Ord, Eq, Show, Gen.Data, Gen.Typeable)
instance RtkPosOf Expr where
    rtkPosOf (Anti_Expr _) = rtkNoPos
    rtkPosOf (Ctr__Expr__0 p _) = p
    rtkPosOf (Ctr__Expr__1 p) = p
    rtkPosOf (Ctr__Expr__2 p) = p
    rtkPosOf (Ctr__Expr__3 p _) = p
    rtkPosOf (Ctr__Expr__5 p _ _) = p
    rtkPosOf (Ctr__Expr__7 p _ _) = p
    rtkPosOf (Ctr__Expr__9 p _ _) = p
    rtkPosOf (Ctr__Expr__10 p _ _) = p
    rtkPosOf (Ctr__Expr__12 p _ _) = p
    rtkPosOf (Ctr__Expr__14 p _ _ _) = p
    rtkPosOf (Ctr__Expr__15 p _ _ _) = p
    rtkPosOf (Ctr__Expr__16 p _ _ _) = p
data Id = Anti_Id String |
          Ctr__Id__0 RtkPos String
          deriving (Ord, Eq, Show, Gen.Data, Gen.Typeable)
instance RtkPosOf Id where
    rtkPosOf (Anti_Id _) = rtkNoPos
    rtkPosOf (Ctr__Id__0 p _) = p
data Ty = Anti_Ty String |
          Ctr__Ty__0 RtkPos |
          Ctr__Ty__1 RtkPos |
          Ctr__Ty__3 RtkPos Ty Ty
          deriving (Ord, Eq, Show, Gen.Data, Gen.Typeable)
instance RtkPosOf Ty where
    rtkPosOf (Anti_Ty _) = rtkNoPos
    rtkPosOf (Ctr__Ty__0 p) = p
    rtkPosOf (Ctr__Ty__1 p) = p
    rtkPosOf (Ctr__Ty__3 p _ _) = p
}