-- Generated by RTK from grammar 'Proto'. Do not edit by hand.
{
{-# LANGUAGE DeriveDataTypeable #-}
module ProtoParser where
import qualified Data.Generics as Gen
import qualified ProtoLexer as L (Token(..), PosToken(..), AlexPosn(..), alexScanTokens)
}

%name parseProto
%tokentype { L.PosToken }
%monad { Either String }
%error { parseError }

%token

rtk__eof { L.PosToken _ L.EndOfFile }
tok_Alt_dummy_25 { L.PosToken _ L.Tk__tok_Alt_dummy_25 }
tok_AltList_dummy_24 { L.PosToken _ L.Tk__tok_AltList_dummy_24 }
tok_ConDef_dummy_23 { L.PosToken _ L.Tk__tok_ConDef_dummy_23 }
tok_ConDefList_dummy_22 { L.PosToken _ L.Tk__tok_ConDefList_dummy_22 }
tok_ConId_dummy_21 { L.PosToken _ L.Tk__tok_ConId_dummy_21 }
tok_Decl_dummy_20 { L.PosToken _ L.Tk__tok_Decl_dummy_20 }
tok_DeclList_dummy_19 { L.PosToken _ L.Tk__tok_DeclList_dummy_19 }
tok_Expr_dummy_18 { L.PosToken _ L.Tk__tok_Expr_dummy_18 }
tok_Field_dummy_17 { L.PosToken _ L.Tk__tok_Field_dummy_17 }
tok_FieldList_dummy_16 { L.PosToken _ L.Tk__tok_FieldList_dummy_16 }
tok_Id_dummy_15 { L.PosToken _ L.Tk__tok_Id_dummy_15 }
tok_PArg_dummy_14 { L.PosToken _ L.Tk__tok_PArg_dummy_14 }
tok_PArgs_dummy_13 { L.PosToken _ L.Tk__tok_PArgs_dummy_13 }
tok_Param_dummy_12 { L.PosToken _ L.Tk__tok_Param_dummy_12 }
tok_Params_dummy_11 { L.PosToken _ L.Tk__tok_Params_dummy_11 }
tok_Pat_dummy_10 { L.PosToken _ L.Tk__tok_Pat_dummy_10 }
tok_Proto_dummy_26 { L.PosToken _ L.Tk__tok_Proto_dummy_26 }
tok_Ty_dummy_9 { L.PosToken _ L.Tk__tok_Ty_dummy_9 }
tok_TyVar_dummy_8 { L.PosToken _ L.Tk__tok_TyVar_dummy_8 }
tok_TyVarList_dummy_7 { L.PosToken _ L.Tk__tok_TyVarList_dummy_7 }
tok__symbol__18 { L.PosToken _ L.Tk__tok__symbol__18 }
tok__pipe__5 { L.PosToken _ L.Tk__tok__pipe__5 }
tok__symbol__17 { L.PosToken _ L.Tk__tok__symbol__17 }
tok_true_20 { L.PosToken _ L.Tk__tok_true_20 }
tok_then_12 { L.PosToken _ L.Tk__tok_then_12 }
tok_rec_4 { L.PosToken _ L.Tk__tok_rec_4 }
tok_of_16 { L.PosToken _ L.Tk__tok_of_16 }
tok_let_3 { L.PosToken _ L.Tk__tok_let_3 }
tok_in_10 { L.PosToken _ L.Tk__tok_in_10 }
tok_if_11 { L.PosToken _ L.Tk__tok_if_11 }
tok_fix_14 { L.PosToken _ L.Tk__tok_fix_14 }
tok_false_21 { L.PosToken _ L.Tk__tok_false_21 }
tok_else_13 { L.PosToken _ L.Tk__tok_else_13 }
tok_data_0 { L.PosToken _ L.Tk__tok_data_0 }
tok_case_15 { L.PosToken _ L.Tk__tok_case_15 }
tok__symbol__19 { L.PosToken _ L.Tk__tok__symbol__19 }
tok__symbol__9 { L.PosToken _ L.Tk__tok__symbol__9 }
tok__eql__eql__22 { L.PosToken _ L.Tk__tok__eql__eql__22 }
tok__eql__1 { L.PosToken _ L.Tk__tok__eql__1 }
tok__semi__2 { L.PosToken _ L.Tk__tok__semi__2 }
tok__minus__symbol__6 { L.PosToken _ L.Tk__tok__minus__symbol__6 }
tok__minus__24 { L.PosToken _ L.Tk__tok__minus__24 }
tok__plus__23 { L.PosToken _ L.Tk__tok__plus__23 }
tok__star__25 { L.PosToken _ L.Tk__tok__star__25 }
tok__rparen__8 { L.PosToken _ L.Tk__tok__rparen__8 }
tok__lparen__7 { L.PosToken _ L.Tk__tok__lparen__7 }
conid { L.PosToken _ (L.Tk__conid _) }
id { L.PosToken _ (L.Tk__id _) }
num { L.PosToken _ (L.Tk__num _) }
qq_Id { L.PosToken _ (L.Tk__qq_Id _) }
qq_ConId { L.PosToken _ (L.Tk__qq_ConId _) }
qq_Param { L.PosToken _ (L.Tk__qq_Param _) }
qq_Params { L.PosToken _ (L.Tk__qq_Params _) }
qq_Expr { L.PosToken _ (L.Tk__qq_Expr _) }
qq_PArg { L.PosToken _ (L.Tk__qq_PArg _) }
qq_PArgs { L.PosToken _ (L.Tk__qq_PArgs _) }
qq_Pat { L.PosToken _ (L.Tk__qq_Pat _) }
qq_Alt { L.PosToken _ (L.Tk__qq_Alt _) }
qq_AltList { L.PosToken _ (L.Tk__qq_AltList _) }
qq_Ty { L.PosToken _ (L.Tk__qq_Ty _) }
qq_Field { L.PosToken _ (L.Tk__qq_Field _) }
qq_FieldList { L.PosToken _ (L.Tk__qq_FieldList _) }
qq_ConDef { L.PosToken _ (L.Tk__qq_ConDef _) }
qq_ConDefList { L.PosToken _ (L.Tk__qq_ConDefList _) }
qq_TyVar { L.PosToken _ (L.Tk__qq_TyVar _) }
qq_TyVarList { L.PosToken _ (L.Tk__qq_TyVarList _) }
qq_Decl { L.PosToken _ (L.Tk__qq_Decl _) }
qq_DeclList { L.PosToken _ (L.Tk__qq_DeclList _) }
qq_Proto { L.PosToken _ (L.Tk__qq_Proto _) }

%%

Proto__top : Proto rtk__eof { $1 }

Proto : tok_Proto_dummy_26 Proto tok_Proto_dummy_26 { Ctr__Proto__0 (rtkPosOf $1) $2 } |
        tok_Alt_dummy_25 Alt tok_Alt_dummy_25 { Ctr__Proto__1 (rtkPosOf $1) $2 } |
        tok_AltList_dummy_24 AltList tok_AltList_dummy_24 { Ctr__Proto__2 (rtkPosOf $1) (reverse $2) } |
        tok_ConDef_dummy_23 ConDef tok_ConDef_dummy_23 { Ctr__Proto__3 (rtkPosOf $1) $2 } |
        tok_ConDefList_dummy_22 ConDefList tok_ConDefList_dummy_22 { Ctr__Proto__4 (rtkPosOf $1) (reverse $2) } |
        tok_ConId_dummy_21 ConId tok_ConId_dummy_21 { Ctr__Proto__5 (rtkPosOf $1) $2 } |
        tok_Decl_dummy_20 Decl tok_Decl_dummy_20 { Ctr__Proto__6 (rtkPosOf $1) $2 } |
        tok_DeclList_dummy_19 DeclList tok_DeclList_dummy_19 { Ctr__Proto__7 (rtkPosOf $1) (reverse $2) } |
        tok_Expr_dummy_18 Expr tok_Expr_dummy_18 { Ctr__Proto__8 (rtkPosOf $1) $2 } |
        tok_Field_dummy_17 Field tok_Field_dummy_17 { Ctr__Proto__9 (rtkPosOf $1) $2 } |
        tok_FieldList_dummy_16 FieldList tok_FieldList_dummy_16 { Ctr__Proto__10 (rtkPosOf $1) (reverse $2) } |
        tok_Id_dummy_15 Id tok_Id_dummy_15 { Ctr__Proto__11 (rtkPosOf $1) $2 } |
        tok_PArg_dummy_14 PArg tok_PArg_dummy_14 { Ctr__Proto__12 (rtkPosOf $1) $2 } |
        tok_PArgs_dummy_13 PArgs tok_PArgs_dummy_13 { Ctr__Proto__13 (rtkPosOf $1) (reverse $2) } |
        tok_Param_dummy_12 Param tok_Param_dummy_12 { Ctr__Proto__14 (rtkPosOf $1) $2 } |
        tok_Params_dummy_11 Params tok_Params_dummy_11 { Ctr__Proto__15 (rtkPosOf $1) (reverse $2) } |
        tok_Pat_dummy_10 Pat tok_Pat_dummy_10 { Ctr__Proto__16 (rtkPosOf $1) $2 } |
        tok_Ty_dummy_9 Ty tok_Ty_dummy_9 { Ctr__Proto__17 (rtkPosOf $1) $2 } |
        tok_TyVar_dummy_8 TyVar tok_TyVar_dummy_8 { Ctr__Proto__18 (rtkPosOf $1) $2 } |
        tok_TyVarList_dummy_7 TyVarList tok_TyVarList_dummy_7 { Ctr__Proto__19 (rtkPosOf $1) (reverse $2) }

Proto : qq_Proto { Anti_Proto (tkVal_qq_Proto $1) } |
        DeclList { Ctr__Proto__20 (rtkPosOf (reverse $1)) (reverse $1) }

Alt : qq_Alt { Anti_Alt (tkVal_qq_Alt $1) } |
      Pat tok__minus__symbol__6 Expr { Ctr__Alt__0 (rtkPosOf $1) $1 $3 }

ListElem_AltList4 : qq_AltList { Anti_Alt (tkVal_qq_AltList $1) } |
                    Alt { $1 }

AltList : ListElem_AltList4 { [$1] } |
          AltList tok__semi__2 ListElem_AltList4 { $3 : $1 }

ConDef : qq_ConDef { Anti_ConDef (tkVal_qq_ConDef $1) } |
         ConId FieldList { Ctr__ConDef__0 (rtkPosOf $1) $1 (reverse $2) }

ListElem_ConDefList2 : qq_ConDefList { Anti_ConDef (tkVal_qq_ConDefList $1) } |
                       ConDef { $1 }

ConDefList : ListElem_ConDefList2 { [$1] } |
             ConDefList tok__pipe__5 ListElem_ConDefList2 { $3 : $1 }

ConId : qq_ConId { Anti_ConId (tkVal_qq_ConId $1) } |
        conid { Ctr__ConId__0 (rtkPosOf $1) (tkVal_conid $1) }

Decl : qq_Decl { Anti_Decl (tkVal_qq_Decl $1) } |
       tok_data_0 ConId TyVarList tok__eql__1 ConDefList tok__semi__2 { Ctr__Decl__0 (rtkPosOf $1) $2 (reverse $3) (reverse $5) } |
       tok_let_3 tok_rec_4 Id tok__eql__1 Expr tok__semi__2 { Ctr__Decl__1 (rtkPosOf $1) $3 $5 } |
       tok_let_3 tok_rec_4 Id Params tok__eql__1 Expr tok__semi__2 { Ctr__Decl__2 (rtkPosOf $1) $3 (reverse $4) $6 } |
       tok_let_3 Id tok__eql__1 Expr tok__semi__2 { Ctr__Decl__3 (rtkPosOf $1) $2 $4 } |
       tok_let_3 Id Params tok__eql__1 Expr tok__semi__2 { Ctr__Decl__4 (rtkPosOf $1) $2 (reverse $3) $5 } |
       Expr tok__semi__2 { Ctr__Decl__5 (rtkPosOf $1) $1 }

ListElem_DeclList0 : qq_DeclList { Anti_Decl (tkVal_qq_DeclList $1) } |
                     Decl { $1 }

DeclList : {- empty -} { [] } |
           DeclList ListElem_DeclList0 { $2 : $1 }

Atom : qq_Expr { Anti_Expr (tkVal_qq_Expr $1) } |
       num { Ctr__Expr__0 (rtkPosOf $1) (tkVal_num $1) } |
       tok_true_20 { Ctr__Expr__1 (rtkPosOf $1) } |
       tok_false_21 { Ctr__Expr__2 (rtkPosOf $1) } |
       Id { Ctr__Expr__3 (rtkPosOf $1) $1 } |
       ConId { Ctr__Expr__4 (rtkPosOf $1) $1 } |
       tok__lparen__7 Expr tok__rparen__8 { $2 }

App : App Atom { Ctr__Expr__6 (rtkPosOf $1) $1 $2 } |
      Atom { $1 }

Mul : Mul tok__star__25 App { Ctr__Expr__8 (rtkPosOf $1) $1 $3 } |
      App { $1 }

Add : Add tok__plus__23 Mul { Ctr__Expr__10 (rtkPosOf $1) $1 $3 } |
      Add tok__minus__24 Mul { Ctr__Expr__11 (rtkPosOf $1) $1 $3 } |
      Mul { $1 }

Eq : Eq tok__eql__eql__22 Add { Ctr__Expr__13 (rtkPosOf $1) $1 $3 } |
     Add { $1 }

Expr : tok__symbol__9 Params tok__minus__symbol__6 Expr { Ctr__Expr__15 (rtkPosOf $1) (reverse $2) $4 } |
       tok_let_3 tok_rec_4 Id tok__eql__1 Expr tok_in_10 Expr { Ctr__Expr__16 (rtkPosOf $1) $3 $5 $7 } |
       tok_let_3 Id tok__eql__1 Expr tok_in_10 Expr { Ctr__Expr__17 (rtkPosOf $1) $2 $4 $6 } |
       tok_if_11 Expr tok_then_12 Expr tok_else_13 Expr { Ctr__Expr__18 (rtkPosOf $1) $2 $4 $6 } |
       tok_fix_14 Expr { Ctr__Expr__19 (rtkPosOf $1) $2 } |
       tok_case_15 Expr tok_of_16 tok__symbol__17 AltList tok__symbol__18 { Ctr__Expr__20 (rtkPosOf $1) $2 (reverse $5) } |
       Eq { $1 }

Field : qq_Field { Anti_Field (tkVal_qq_Field $1) } |
        TyAtom { Ctr__Field__0 (rtkPosOf $1) $1 }

ListElem_FieldList3 : qq_FieldList { Anti_Field (tkVal_qq_FieldList $1) } |
                      Field { $1 }

FieldList : {- empty -} { [] } |
            FieldList ListElem_FieldList3 { $2 : $1 }

Id : qq_Id { Anti_Id (tkVal_qq_Id $1) } |
     id { Ctr__Id__0 (rtkPosOf $1) (tkVal_id $1) }

PArg : qq_PArg { Anti_PArg (tkVal_qq_PArg $1) } |
       PatAtom { Ctr__PArg__0 (rtkPosOf $1) $1 }

ListElem_PArgs5 : qq_PArgs { Anti_PArg (tkVal_qq_PArgs $1) } |
                  PArg { $1 }

PArgs : ListElem_PArgs5 { [$1] } |
        PArgs ListElem_PArgs5 { $2 : $1 }

Param : qq_Param { Anti_Param (tkVal_qq_Param $1) } |
        Id { Ctr__Param__0 (rtkPosOf $1) $1 }

ListElem_Params6 : qq_Params { Anti_Param (tkVal_qq_Params $1) } |
                   Param { $1 }

Params : ListElem_Params6 { [$1] } |
         Params ListElem_Params6 { $2 : $1 }

PatAtom : qq_Pat { Anti_Pat (tkVal_qq_Pat $1) } |
          num { Ctr__Pat__0 (rtkPosOf $1) (tkVal_num $1) } |
          tok__symbol__19 { Ctr__Pat__1 (rtkPosOf $1) } |
          tok_true_20 { Ctr__Pat__2 (rtkPosOf $1) } |
          tok_false_21 { Ctr__Pat__3 (rtkPosOf $1) } |
          Id { Ctr__Pat__4 (rtkPosOf $1) $1 } |
          ConId { Ctr__Pat__5 (rtkPosOf $1) $1 } |
          tok__lparen__7 Pat tok__rparen__8 { $2 }

Pat : ConId PArgs { Ctr__Pat__7 (rtkPosOf $1) $1 (reverse $2) } |
      PatAtom { $1 }

TyAtom : qq_Ty { Anti_Ty (tkVal_qq_Ty $1) } |
         ConId { Ctr__Ty__0 (rtkPosOf $1) $1 } |
         Id { Ctr__Ty__1 (rtkPosOf $1) $1 } |
         tok__lparen__7 Ty tok__rparen__8 { $2 }

TyApp : TyApp TyAtom { Ctr__Ty__3 (rtkPosOf $1) $1 $2 } |
        TyAtom { $1 }

Ty : TyApp tok__minus__symbol__6 Ty { Ctr__Ty__5 (rtkPosOf $1) $1 $3 } |
     TyApp { $1 }

TyVar : qq_TyVar { Anti_TyVar (tkVal_qq_TyVar $1) } |
        Id { Ctr__TyVar__0 (rtkPosOf $1) $1 }

ListElem_TyVarList1 : qq_TyVarList { Anti_TyVar (tkVal_qq_TyVarList $1) } |
                      TyVar { $1 }

TyVarList : {- empty -} { [] } |
            TyVarList ListElem_TyVarList1 { $2 : $1 }


{
parseError :: [L.PosToken] -> Either String a
parseError [] = Left "unexpected end of input"
parseError (L.PosToken (L.AlexPn _ line col) tok : _) =
    Left $ show line ++ ":" ++ show col ++ ":unexpected " ++ showRtkToken tok

-- Render a token the way it appears in the source, for error messages
showRtkToken :: L.Token -> String
showRtkToken L.EndOfFile = "end of input"
showRtkToken L.Tk__tok_Alt_dummy_25 = "'tok_Alt_dummy_25'"
showRtkToken L.Tk__tok_AltList_dummy_24 = "'tok_AltList_dummy_24'"
showRtkToken L.Tk__tok_ConDef_dummy_23 = "'tok_ConDef_dummy_23'"
showRtkToken L.Tk__tok_ConDefList_dummy_22 = "'tok_ConDefList_dummy_22'"
showRtkToken L.Tk__tok_ConId_dummy_21 = "'tok_ConId_dummy_21'"
showRtkToken L.Tk__tok_Decl_dummy_20 = "'tok_Decl_dummy_20'"
showRtkToken L.Tk__tok_DeclList_dummy_19 = "'tok_DeclList_dummy_19'"
showRtkToken L.Tk__tok_Expr_dummy_18 = "'tok_Expr_dummy_18'"
showRtkToken L.Tk__tok_Field_dummy_17 = "'tok_Field_dummy_17'"
showRtkToken L.Tk__tok_FieldList_dummy_16 = "'tok_FieldList_dummy_16'"
showRtkToken L.Tk__tok_Id_dummy_15 = "'tok_Id_dummy_15'"
showRtkToken L.Tk__tok_PArg_dummy_14 = "'tok_PArg_dummy_14'"
showRtkToken L.Tk__tok_PArgs_dummy_13 = "'tok_PArgs_dummy_13'"
showRtkToken L.Tk__tok_Param_dummy_12 = "'tok_Param_dummy_12'"
showRtkToken L.Tk__tok_Params_dummy_11 = "'tok_Params_dummy_11'"
showRtkToken L.Tk__tok_Pat_dummy_10 = "'tok_Pat_dummy_10'"
showRtkToken L.Tk__tok_Proto_dummy_26 = "'tok_Proto_dummy_26'"
showRtkToken L.Tk__tok_Ty_dummy_9 = "'tok_Ty_dummy_9'"
showRtkToken L.Tk__tok_TyVar_dummy_8 = "'tok_TyVar_dummy_8'"
showRtkToken L.Tk__tok_TyVarList_dummy_7 = "'tok_TyVarList_dummy_7'"
showRtkToken L.Tk__tok__symbol__18 = "'}'"
showRtkToken L.Tk__tok__pipe__5 = "'|'"
showRtkToken L.Tk__tok__symbol__17 = "'{'"
showRtkToken L.Tk__tok_true_20 = "'true'"
showRtkToken L.Tk__tok_then_12 = "'then'"
showRtkToken L.Tk__tok_rec_4 = "'rec'"
showRtkToken L.Tk__tok_of_16 = "'of'"
showRtkToken L.Tk__tok_let_3 = "'let'"
showRtkToken L.Tk__tok_in_10 = "'in'"
showRtkToken L.Tk__tok_if_11 = "'if'"
showRtkToken L.Tk__tok_fix_14 = "'fix'"
showRtkToken L.Tk__tok_false_21 = "'false'"
showRtkToken L.Tk__tok_else_13 = "'else'"
showRtkToken L.Tk__tok_data_0 = "'data'"
showRtkToken L.Tk__tok_case_15 = "'case'"
showRtkToken L.Tk__tok__symbol__19 = "'_'"
showRtkToken L.Tk__tok__symbol__9 = "'\\'"
showRtkToken L.Tk__tok__eql__eql__22 = "'=='"
showRtkToken L.Tk__tok__eql__1 = "'='"
showRtkToken L.Tk__tok__semi__2 = "';'"
showRtkToken L.Tk__tok__minus__symbol__6 = "'->'"
showRtkToken L.Tk__tok__minus__24 = "'-'"
showRtkToken L.Tk__tok__plus__23 = "'+'"
showRtkToken L.Tk__tok__star__25 = "'*'"
showRtkToken L.Tk__tok__rparen__8 = "')'"
showRtkToken L.Tk__tok__lparen__7 = "'('"
showRtkToken (L.Tk__conid v) = "conid " ++ show v
showRtkToken (L.Tk__id v) = "id " ++ show v
showRtkToken (L.Tk__num v) = "num " ++ show v
showRtkToken (L.Tk__qq_Id v) = "qq_Id " ++ show v
showRtkToken (L.Tk__qq_ConId v) = "qq_ConId " ++ show v
showRtkToken (L.Tk__qq_Param v) = "qq_Param " ++ show v
showRtkToken (L.Tk__qq_Params v) = "qq_Params " ++ show v
showRtkToken (L.Tk__qq_Expr v) = "qq_Expr " ++ show v
showRtkToken (L.Tk__qq_PArg v) = "qq_PArg " ++ show v
showRtkToken (L.Tk__qq_PArgs v) = "qq_PArgs " ++ show v
showRtkToken (L.Tk__qq_Pat v) = "qq_Pat " ++ show v
showRtkToken (L.Tk__qq_Alt v) = "qq_Alt " ++ show v
showRtkToken (L.Tk__qq_AltList v) = "qq_AltList " ++ show v
showRtkToken (L.Tk__qq_Ty v) = "qq_Ty " ++ show v
showRtkToken (L.Tk__qq_Field v) = "qq_Field " ++ show v
showRtkToken (L.Tk__qq_FieldList v) = "qq_FieldList " ++ show v
showRtkToken (L.Tk__qq_ConDef v) = "qq_ConDef " ++ show v
showRtkToken (L.Tk__qq_ConDefList v) = "qq_ConDefList " ++ show v
showRtkToken (L.Tk__qq_TyVar v) = "qq_TyVar " ++ show v
showRtkToken (L.Tk__qq_TyVarList v) = "qq_TyVarList " ++ show v
showRtkToken (L.Tk__qq_Decl v) = "qq_Decl " ++ show v
showRtkToken (L.Tk__qq_DeclList v) = "qq_DeclList " ++ show v
showRtkToken (L.Tk__qq_Proto v) = "qq_Proto " ++ show v

-- Source position of a node: every constructor except the Anti_* splice
-- artifacts stores the position of its alternative's first symbol in its
-- first field. Positions are transparent for equality and ordering, so two
-- ASTs that differ only in source positions (e.g. a quasi-quote parsed at
-- compile time vs the same construct parsed at run time) compare equal.
newtype RtkPos = RtkPos L.AlexPosn deriving (Show, Gen.Data, Gen.Typeable)
instance Eq RtkPos where _ == _ = True
instance Ord RtkPos where compare _ _ = EQ

-- The position used where no source token exists: empty productions, empty
-- lists, absent optionals and Anti_* quasi-quote splices
rtkNoPos :: RtkPos
rtkNoPos = RtkPos (L.AlexPn 0 0 0)

class RtkPosOf a where
    rtkPosOf :: a -> RtkPos
instance RtkPosOf L.PosToken where
    rtkPosOf (L.PosToken p _) = RtkPos p
instance RtkPosOf a => RtkPosOf [a] where
    rtkPosOf (x : _) = rtkPosOf x
    rtkPosOf []      = rtkNoPos
instance RtkPosOf a => RtkPosOf (Maybe a) where
    rtkPosOf (Just x) = rtkPosOf x
    rtkPosOf Nothing  = rtkNoPos
-- A Char carries no position; this also covers String token payloads
instance RtkPosOf Char where
    rtkPosOf _ = rtkNoPos
instance RtkPosOf Int where rtkPosOf _ = rtkNoPos

-- Recover a token's payload from the whole positioned token: %token
-- bindings keep the L.PosToken so semantic actions can read its position
tkVal_conid :: L.PosToken -> String
tkVal_conid (L.PosToken _ (L.Tk__conid v)) = v
tkVal_conid t = error ("rtk internal error: token conid expected, got " ++ showRtkToken (L.ptToken t))
tkVal_id :: L.PosToken -> String
tkVal_id (L.PosToken _ (L.Tk__id v)) = v
tkVal_id t = error ("rtk internal error: token id expected, got " ++ showRtkToken (L.ptToken t))
tkVal_num :: L.PosToken -> Int
tkVal_num (L.PosToken _ (L.Tk__num v)) = v
tkVal_num t = error ("rtk internal error: token num expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_Id :: L.PosToken -> String
tkVal_qq_Id (L.PosToken _ (L.Tk__qq_Id v)) = v
tkVal_qq_Id t = error ("rtk internal error: token qq_Id expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_ConId :: L.PosToken -> String
tkVal_qq_ConId (L.PosToken _ (L.Tk__qq_ConId v)) = v
tkVal_qq_ConId t = error ("rtk internal error: token qq_ConId expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_Param :: L.PosToken -> String
tkVal_qq_Param (L.PosToken _ (L.Tk__qq_Param v)) = v
tkVal_qq_Param t = error ("rtk internal error: token qq_Param expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_Params :: L.PosToken -> String
tkVal_qq_Params (L.PosToken _ (L.Tk__qq_Params v)) = v
tkVal_qq_Params t = error ("rtk internal error: token qq_Params expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_Expr :: L.PosToken -> String
tkVal_qq_Expr (L.PosToken _ (L.Tk__qq_Expr v)) = v
tkVal_qq_Expr t = error ("rtk internal error: token qq_Expr expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_PArg :: L.PosToken -> String
tkVal_qq_PArg (L.PosToken _ (L.Tk__qq_PArg v)) = v
tkVal_qq_PArg t = error ("rtk internal error: token qq_PArg expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_PArgs :: L.PosToken -> String
tkVal_qq_PArgs (L.PosToken _ (L.Tk__qq_PArgs v)) = v
tkVal_qq_PArgs t = error ("rtk internal error: token qq_PArgs expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_Pat :: L.PosToken -> String
tkVal_qq_Pat (L.PosToken _ (L.Tk__qq_Pat v)) = v
tkVal_qq_Pat t = error ("rtk internal error: token qq_Pat expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_Alt :: L.PosToken -> String
tkVal_qq_Alt (L.PosToken _ (L.Tk__qq_Alt v)) = v
tkVal_qq_Alt t = error ("rtk internal error: token qq_Alt expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_AltList :: L.PosToken -> String
tkVal_qq_AltList (L.PosToken _ (L.Tk__qq_AltList v)) = v
tkVal_qq_AltList t = error ("rtk internal error: token qq_AltList expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_Ty :: L.PosToken -> String
tkVal_qq_Ty (L.PosToken _ (L.Tk__qq_Ty v)) = v
tkVal_qq_Ty t = error ("rtk internal error: token qq_Ty expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_Field :: L.PosToken -> String
tkVal_qq_Field (L.PosToken _ (L.Tk__qq_Field v)) = v
tkVal_qq_Field t = error ("rtk internal error: token qq_Field expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_FieldList :: L.PosToken -> String
tkVal_qq_FieldList (L.PosToken _ (L.Tk__qq_FieldList v)) = v
tkVal_qq_FieldList t = error ("rtk internal error: token qq_FieldList expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_ConDef :: L.PosToken -> String
tkVal_qq_ConDef (L.PosToken _ (L.Tk__qq_ConDef v)) = v
tkVal_qq_ConDef t = error ("rtk internal error: token qq_ConDef expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_ConDefList :: L.PosToken -> String
tkVal_qq_ConDefList (L.PosToken _ (L.Tk__qq_ConDefList v)) = v
tkVal_qq_ConDefList t = error ("rtk internal error: token qq_ConDefList expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_TyVar :: L.PosToken -> String
tkVal_qq_TyVar (L.PosToken _ (L.Tk__qq_TyVar v)) = v
tkVal_qq_TyVar t = error ("rtk internal error: token qq_TyVar expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_TyVarList :: L.PosToken -> String
tkVal_qq_TyVarList (L.PosToken _ (L.Tk__qq_TyVarList v)) = v
tkVal_qq_TyVarList t = error ("rtk internal error: token qq_TyVarList expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_Decl :: L.PosToken -> String
tkVal_qq_Decl (L.PosToken _ (L.Tk__qq_Decl v)) = v
tkVal_qq_Decl t = error ("rtk internal error: token qq_Decl expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_DeclList :: L.PosToken -> String
tkVal_qq_DeclList (L.PosToken _ (L.Tk__qq_DeclList v)) = v
tkVal_qq_DeclList t = error ("rtk internal error: token qq_DeclList expected, got " ++ showRtkToken (L.ptToken t))
tkVal_qq_Proto :: L.PosToken -> String
tkVal_qq_Proto (L.PosToken _ (L.Tk__qq_Proto v)) = v
tkVal_qq_Proto t = error ("rtk internal error: token qq_Proto expected, got " ++ showRtkToken (L.ptToken t))

data Proto = Ctr__Proto__0 RtkPos Proto |
             Ctr__Proto__1 RtkPos Alt |
             Ctr__Proto__2 RtkPos AltList |
             Ctr__Proto__3 RtkPos ConDef |
             Ctr__Proto__4 RtkPos ConDefList |
             Ctr__Proto__5 RtkPos ConId |
             Ctr__Proto__6 RtkPos Decl |
             Ctr__Proto__7 RtkPos DeclList |
             Ctr__Proto__8 RtkPos Expr |
             Ctr__Proto__9 RtkPos Field |
             Ctr__Proto__10 RtkPos FieldList |
             Ctr__Proto__11 RtkPos Id |
             Ctr__Proto__12 RtkPos PArg |
             Ctr__Proto__13 RtkPos PArgs |
             Ctr__Proto__14 RtkPos Param |
             Ctr__Proto__15 RtkPos Params |
             Ctr__Proto__16 RtkPos Pat |
             Ctr__Proto__17 RtkPos Ty |
             Ctr__Proto__18 RtkPos TyVar |
             Ctr__Proto__19 RtkPos TyVarList |
             Anti_Proto String |
             Ctr__Proto__20 RtkPos DeclList
             deriving (Ord, Eq, Show, Gen.Data, Gen.Typeable)
instance RtkPosOf Proto where
    rtkPosOf (Ctr__Proto__0 p _) = p
    rtkPosOf (Ctr__Proto__1 p _) = p
    rtkPosOf (Ctr__Proto__2 p _) = p
    rtkPosOf (Ctr__Proto__3 p _) = p
    rtkPosOf (Ctr__Proto__4 p _) = p
    rtkPosOf (Ctr__Proto__5 p _) = p
    rtkPosOf (Ctr__Proto__6 p _) = p
    rtkPosOf (Ctr__Proto__7 p _) = p
    rtkPosOf (Ctr__Proto__8 p _) = p
    rtkPosOf (Ctr__Proto__9 p _) = p
    rtkPosOf (Ctr__Proto__10 p _) = p
    rtkPosOf (Ctr__Proto__11 p _) = p
    rtkPosOf (Ctr__Proto__12 p _) = p
    rtkPosOf (Ctr__Proto__13 p _) = p
    rtkPosOf (Ctr__Proto__14 p _) = p
    rtkPosOf (Ctr__Proto__15 p _) = p
    rtkPosOf (Ctr__Proto__16 p _) = p
    rtkPosOf (Ctr__Proto__17 p _) = p
    rtkPosOf (Ctr__Proto__18 p _) = p
    rtkPosOf (Ctr__Proto__19 p _) = p
    rtkPosOf (Anti_Proto _) = rtkNoPos
    rtkPosOf (Ctr__Proto__20 p _) = p
data Alt = Anti_Alt String |
           Ctr__Alt__0 RtkPos Pat Expr
           deriving (Ord, Eq, Show, Gen.Data, Gen.Typeable)
instance RtkPosOf Alt where
    rtkPosOf (Anti_Alt _) = rtkNoPos
    rtkPosOf (Ctr__Alt__0 p _ _) = p
type AltList = [Alt]
data ConDef = Anti_ConDef String |
              Ctr__ConDef__0 RtkPos ConId FieldList
              deriving (Ord, Eq, Show, Gen.Data, Gen.Typeable)
instance RtkPosOf ConDef where
    rtkPosOf (Anti_ConDef _) = rtkNoPos
    rtkPosOf (Ctr__ConDef__0 p _ _) = p
type ConDefList = [ConDef]
data ConId = Anti_ConId String |
             Ctr__ConId__0 RtkPos String
             deriving (Ord, Eq, Show, Gen.Data, Gen.Typeable)
instance RtkPosOf ConId where
    rtkPosOf (Anti_ConId _) = rtkNoPos
    rtkPosOf (Ctr__ConId__0 p _) = p
data Decl = Anti_Decl String |
            Ctr__Decl__0 RtkPos ConId TyVarList ConDefList |
            Ctr__Decl__1 RtkPos Id Expr |
            Ctr__Decl__2 RtkPos Id Params Expr |
            Ctr__Decl__3 RtkPos Id Expr |
            Ctr__Decl__4 RtkPos Id Params Expr |
            Ctr__Decl__5 RtkPos Expr
            deriving (Ord, Eq, Show, Gen.Data, Gen.Typeable)
instance RtkPosOf Decl where
    rtkPosOf (Anti_Decl _) = rtkNoPos
    rtkPosOf (Ctr__Decl__0 p _ _ _) = p
    rtkPosOf (Ctr__Decl__1 p _ _) = p
    rtkPosOf (Ctr__Decl__2 p _ _ _) = p
    rtkPosOf (Ctr__Decl__3 p _ _) = p
    rtkPosOf (Ctr__Decl__4 p _ _ _) = p
    rtkPosOf (Ctr__Decl__5 p _) = p
type DeclList = [Decl]
data Expr = Anti_Expr String |
            Ctr__Expr__0 RtkPos Int |
            Ctr__Expr__1 RtkPos |
            Ctr__Expr__2 RtkPos |
            Ctr__Expr__3 RtkPos Id |
            Ctr__Expr__4 RtkPos ConId |
            Ctr__Expr__6 RtkPos Expr Expr |
            Ctr__Expr__8 RtkPos Expr Expr |
            Ctr__Expr__10 RtkPos Expr Expr |
            Ctr__Expr__11 RtkPos Expr Expr |
            Ctr__Expr__13 RtkPos Expr Expr |
            Ctr__Expr__15 RtkPos Params Expr |
            Ctr__Expr__16 RtkPos Id Expr Expr |
            Ctr__Expr__17 RtkPos Id Expr Expr |
            Ctr__Expr__18 RtkPos Expr Expr Expr |
            Ctr__Expr__19 RtkPos Expr |
            Ctr__Expr__20 RtkPos Expr AltList
            deriving (Ord, Eq, Show, Gen.Data, Gen.Typeable)
instance RtkPosOf Expr where
    rtkPosOf (Anti_Expr _) = rtkNoPos
    rtkPosOf (Ctr__Expr__0 p _) = p
    rtkPosOf (Ctr__Expr__1 p) = p
    rtkPosOf (Ctr__Expr__2 p) = p
    rtkPosOf (Ctr__Expr__3 p _) = p
    rtkPosOf (Ctr__Expr__4 p _) = p
    rtkPosOf (Ctr__Expr__6 p _ _) = p
    rtkPosOf (Ctr__Expr__8 p _ _) = p
    rtkPosOf (Ctr__Expr__10 p _ _) = p
    rtkPosOf (Ctr__Expr__11 p _ _) = p
    rtkPosOf (Ctr__Expr__13 p _ _) = p
    rtkPosOf (Ctr__Expr__15 p _ _) = p
    rtkPosOf (Ctr__Expr__16 p _ _ _) = p
    rtkPosOf (Ctr__Expr__17 p _ _ _) = p
    rtkPosOf (Ctr__Expr__18 p _ _ _) = p
    rtkPosOf (Ctr__Expr__19 p _) = p
    rtkPosOf (Ctr__Expr__20 p _ _) = p
data Field = Anti_Field String |
             Ctr__Field__0 RtkPos Ty
             deriving (Ord, Eq, Show, Gen.Data, Gen.Typeable)
instance RtkPosOf Field where
    rtkPosOf (Anti_Field _) = rtkNoPos
    rtkPosOf (Ctr__Field__0 p _) = p
type FieldList = [Field]
data Id = Anti_Id String |
          Ctr__Id__0 RtkPos String
          deriving (Ord, Eq, Show, Gen.Data, Gen.Typeable)
instance RtkPosOf Id where
    rtkPosOf (Anti_Id _) = rtkNoPos
    rtkPosOf (Ctr__Id__0 p _) = p
data PArg = Anti_PArg String |
            Ctr__PArg__0 RtkPos Pat
            deriving (Ord, Eq, Show, Gen.Data, Gen.Typeable)
instance RtkPosOf PArg where
    rtkPosOf (Anti_PArg _) = rtkNoPos
    rtkPosOf (Ctr__PArg__0 p _) = p
type PArgs = [PArg]
data Param = Anti_Param String |
             Ctr__Param__0 RtkPos Id
             deriving (Ord, Eq, Show, Gen.Data, Gen.Typeable)
instance RtkPosOf Param where
    rtkPosOf (Anti_Param _) = rtkNoPos
    rtkPosOf (Ctr__Param__0 p _) = p
type Params = [Param]
data Pat = Anti_Pat String |
           Ctr__Pat__0 RtkPos Int |
           Ctr__Pat__1 RtkPos |
           Ctr__Pat__2 RtkPos |
           Ctr__Pat__3 RtkPos |
           Ctr__Pat__4 RtkPos Id |
           Ctr__Pat__5 RtkPos ConId |
           Ctr__Pat__7 RtkPos ConId PArgs
           deriving (Ord, Eq, Show, Gen.Data, Gen.Typeable)
instance RtkPosOf Pat where
    rtkPosOf (Anti_Pat _) = rtkNoPos
    rtkPosOf (Ctr__Pat__0 p _) = p
    rtkPosOf (Ctr__Pat__1 p) = p
    rtkPosOf (Ctr__Pat__2 p) = p
    rtkPosOf (Ctr__Pat__3 p) = p
    rtkPosOf (Ctr__Pat__4 p _) = p
    rtkPosOf (Ctr__Pat__5 p _) = p
    rtkPosOf (Ctr__Pat__7 p _ _) = p
data Ty = Anti_Ty String |
          Ctr__Ty__0 RtkPos ConId |
          Ctr__Ty__1 RtkPos Id |
          Ctr__Ty__3 RtkPos Ty Ty |
          Ctr__Ty__5 RtkPos Ty Ty
          deriving (Ord, Eq, Show, Gen.Data, Gen.Typeable)
instance RtkPosOf Ty where
    rtkPosOf (Anti_Ty _) = rtkNoPos
    rtkPosOf (Ctr__Ty__0 p _) = p
    rtkPosOf (Ctr__Ty__1 p _) = p
    rtkPosOf (Ctr__Ty__3 p _ _) = p
    rtkPosOf (Ctr__Ty__5 p _ _) = p
data TyVar = Anti_TyVar String |
             Ctr__TyVar__0 RtkPos Id
             deriving (Ord, Eq, Show, Gen.Data, Gen.Typeable)
instance RtkPosOf TyVar where
    rtkPosOf (Anti_TyVar _) = rtkNoPos
    rtkPosOf (Ctr__TyVar__0 p _) = p
type TyVarList = [TyVar]
}