-- Generated by RTK from grammar 'Proto'. Do not edit by hand.
{
{-# LANGUAGE StandaloneDeriving, DeriveDataTypeable #-}
module ProtoLexer(scanTokens, alexScanTokens, Token(..), PosToken(..), AlexPosn(..))
where
import Data.Data (Data)

 }
%wrapper "monad"


tokens :- "tok_Alt_dummy_25" { simple Tk__tok_Alt_dummy_25 }
          "tok_AltList_dummy_24" { simple Tk__tok_AltList_dummy_24 }
          "tok_ConDef_dummy_23" { simple Tk__tok_ConDef_dummy_23 }
          "tok_ConDefList_dummy_22" { simple Tk__tok_ConDefList_dummy_22 }
          "tok_ConId_dummy_21" { simple Tk__tok_ConId_dummy_21 }
          "tok_Decl_dummy_20" { simple Tk__tok_Decl_dummy_20 }
          "tok_DeclList_dummy_19" { simple Tk__tok_DeclList_dummy_19 }
          "tok_Expr_dummy_18" { simple Tk__tok_Expr_dummy_18 }
          "tok_Field_dummy_17" { simple Tk__tok_Field_dummy_17 }
          "tok_FieldList_dummy_16" { simple Tk__tok_FieldList_dummy_16 }
          "tok_Id_dummy_15" { simple Tk__tok_Id_dummy_15 }
          "tok_PArg_dummy_14" { simple Tk__tok_PArg_dummy_14 }
          "tok_PArgs_dummy_13" { simple Tk__tok_PArgs_dummy_13 }
          "tok_Param_dummy_12" { simple Tk__tok_Param_dummy_12 }
          "tok_Params_dummy_11" { simple Tk__tok_Params_dummy_11 }
          "tok_Pat_dummy_10" { simple Tk__tok_Pat_dummy_10 }
          "tok_Proto_dummy_26" { simple Tk__tok_Proto_dummy_26 }
          "tok_Ty_dummy_9" { simple Tk__tok_Ty_dummy_9 }
          "tok_TyVar_dummy_8" { simple Tk__tok_TyVar_dummy_8 }
          "tok_TyVarList_dummy_7" { simple Tk__tok_TyVarList_dummy_7 }
          "}" { simple Tk__tok__symbol__18 }
          "|" { simple Tk__tok__pipe__5 }
          "{" { simple Tk__tok__symbol__17 }
          "true" { simple Tk__tok_true_20 }
          "then" { simple Tk__tok_then_12 }
          "rec" { simple Tk__tok_rec_4 }
          "of" { simple Tk__tok_of_16 }
          "let" { simple Tk__tok_let_3 }
          "in" { simple Tk__tok_in_10 }
          "if" { simple Tk__tok_if_11 }
          "fix" { simple Tk__tok_fix_14 }
          "false" { simple Tk__tok_false_21 }
          "else" { simple Tk__tok_else_13 }
          "data" { simple Tk__tok_data_0 }
          "case" { simple Tk__tok_case_15 }
          "_" { simple Tk__tok__symbol__19 }
          "\" { simple Tk__tok__symbol__9 }
          "==" { simple Tk__tok__eql__eql__22 }
          "=" { simple Tk__tok__eql__1 }
          ";" { simple Tk__tok__semi__2 }
          "->" { simple Tk__tok__minus__symbol__6 }
          "-" { simple Tk__tok__minus__24 }
          "+" { simple Tk__tok__plus__23 }
          "*" { simple Tk__tok__star__25 }
          ")" { simple Tk__tok__rparen__8 }
          "(" { simple Tk__tok__lparen__7 }
          ("--"  .*  [\n]) ;
          ([\ \t\n]+) ;
          ([A-Z]  [a-zA-Z0-9_]*) { simple1 $  Tk__conid . (id) }
          ([a-z]  [a-zA-Z0-9_]*) { simple1 $  Tk__id . (id) }
          ([0-9]+) { simple1 $  Tk__num . (read) }
          ("$"  "Id"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Id . ((tail . dropWhile (/= ':'))) }
          ("$"  "ConId"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_ConId . ((tail . dropWhile (/= ':'))) }
          ("$"  "Param"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Param . ((tail . dropWhile (/= ':'))) }
          ("$"  "Params"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Params . ((tail . dropWhile (/= ':'))) }
          ("$"  "Expr"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Expr . ((tail . dropWhile (/= ':'))) }
          ("$"  "PArg"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_PArg . ((tail . dropWhile (/= ':'))) }
          ("$"  "PArgs"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_PArgs . ((tail . dropWhile (/= ':'))) }
          ("$"  "Pat"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Pat . ((tail . dropWhile (/= ':'))) }
          ("$"  "Alt"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Alt . ((tail . dropWhile (/= ':'))) }
          ("$"  "AltList"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_AltList . ((tail . dropWhile (/= ':'))) }
          ("$"  "Ty"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Ty . ((tail . dropWhile (/= ':'))) }
          ("$"  "Field"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Field . ((tail . dropWhile (/= ':'))) }
          ("$"  "FieldList"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_FieldList . ((tail . dropWhile (/= ':'))) }
          ("$"  "ConDef"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_ConDef . ((tail . dropWhile (/= ':'))) }
          ("$"  "ConDefList"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_ConDefList . ((tail . dropWhile (/= ':'))) }
          ("$"  "TyVar"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_TyVar . ((tail . dropWhile (/= ':'))) }
          ("$"  "TyVarList"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_TyVarList . ((tail . dropWhile (/= ':'))) }
          ("$"  "Decl"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Decl . ((tail . dropWhile (/= ':'))) }
          ("$"  "DeclList"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_DeclList . ((tail . dropWhile (/= ':'))) }
          ("$"  "Proto"  ":"  [a-zA-Z_]  [A-Za-z0-9_]*) { simple1 $  Tk__qq_Proto . ((tail . dropWhile (/= ':'))) }
          . { rtkError }

{
data Token = EndOfFile |
             Tk__tok_Alt_dummy_25 |
             Tk__tok_AltList_dummy_24 |
             Tk__tok_ConDef_dummy_23 |
             Tk__tok_ConDefList_dummy_22 |
             Tk__tok_ConId_dummy_21 |
             Tk__tok_Decl_dummy_20 |
             Tk__tok_DeclList_dummy_19 |
             Tk__tok_Expr_dummy_18 |
             Tk__tok_Field_dummy_17 |
             Tk__tok_FieldList_dummy_16 |
             Tk__tok_Id_dummy_15 |
             Tk__tok_PArg_dummy_14 |
             Tk__tok_PArgs_dummy_13 |
             Tk__tok_Param_dummy_12 |
             Tk__tok_Params_dummy_11 |
             Tk__tok_Pat_dummy_10 |
             Tk__tok_Proto_dummy_26 |
             Tk__tok_Ty_dummy_9 |
             Tk__tok_TyVar_dummy_8 |
             Tk__tok_TyVarList_dummy_7 |
             Tk__tok__symbol__18 |
             Tk__tok__pipe__5 |
             Tk__tok__symbol__17 |
             Tk__tok_true_20 |
             Tk__tok_then_12 |
             Tk__tok_rec_4 |
             Tk__tok_of_16 |
             Tk__tok_let_3 |
             Tk__tok_in_10 |
             Tk__tok_if_11 |
             Tk__tok_fix_14 |
             Tk__tok_false_21 |
             Tk__tok_else_13 |
             Tk__tok_data_0 |
             Tk__tok_case_15 |
             Tk__tok__symbol__19 |
             Tk__tok__symbol__9 |
             Tk__tok__eql__eql__22 |
             Tk__tok__eql__1 |
             Tk__tok__semi__2 |
             Tk__tok__minus__symbol__6 |
             Tk__tok__minus__24 |
             Tk__tok__plus__23 |
             Tk__tok__star__25 |
             Tk__tok__rparen__8 |
             Tk__tok__lparen__7 |
             Tk__conid String |
             Tk__id String |
             Tk__num Int |
             Tk__qq_Id String |
             Tk__qq_ConId String |
             Tk__qq_Param String |
             Tk__qq_Params String |
             Tk__qq_Expr String |
             Tk__qq_PArg String |
             Tk__qq_PArgs String |
             Tk__qq_Pat String |
             Tk__qq_Alt String |
             Tk__qq_AltList String |
             Tk__qq_Ty String |
             Tk__qq_Field String |
             Tk__qq_FieldList String |
             Tk__qq_ConDef String |
             Tk__qq_ConDefList String |
             Tk__qq_TyVar String |
             Tk__qq_TyVarList String |
             Tk__qq_Decl String |
             Tk__qq_DeclList String |
             Tk__qq_Proto String
             deriving (Show)

-- AlexPosn is defined by the alex wrapper, so the Data instance (required by
-- the parser's RtkPos position type) can only be attached via standalone
-- deriving - the same solution as the hand-written Lexer.x
deriving instance Data AlexPosn

-- A token together with the source position where it starts
data PosToken = PosToken { ptPos :: AlexPosn, ptToken :: Token }
                deriving (Show)

alexEOF = do
  (pos, _, _, _) <- alexGetInput
  return $ PosToken pos EndOfFile

-- Lex the input into a token stream, returning the positioned error message
-- on a lexical error (encoded as "LINE:COL:message", see rtkError below).
-- The returned list always ends with an EndOfFile token that carries the
-- position of the end of input, so parse errors at end of input can be
-- reported with a position too
scanTokens :: String -> Either String [PosToken]
scanTokens str = runAlex str $ do
  let loop toks = do tok <- alexMonadScan
                     case tok of
                       PosToken _ EndOfFile -> return $ reverse (tok : toks)
                       _ -> let toks' = tok : toks
                            in toks' `seq` loop toks'
  loop []

-- Thin compatibility wrapper: callers that have not switched to 'scanTokens'
-- get the error message thrown instead
alexScanTokens :: String -> [PosToken]
alexScanTokens str =
               case scanTokens str of
                  Right toks -> toks
                  Left err -> errorWithoutStackTrace err

simple1 :: (String -> Token) -> AlexInput -> Int -> Alex PosToken
simple1 t (pos, _, _, str) len = return $ PosToken pos (t (take len str))

simple :: Token -> AlexInput -> Int -> Alex PosToken
simple t (pos, _, _, _) len = return $ PosToken pos t

-- Encode the position as "LINE:COL:message" so callers can split it back out
-- into a structured position - the same encoding the rtk grammar lexer uses
rtkError ((AlexPn _ line column), _, _, str) len = alexError $ (show line) ++ ":" ++ (show column) ++ ":lexical error. Following chars: " ++ (take 10 str)

}